branches:
  only:
    - main
language: node_js
services:
  - docker
node_js:
  - '15'
cache:
  directories:
  - node_modules
install:
  - npm install
scripts:
  - npm install -g codecov
  - npm run test
  - npm run test:cov
after_success:
  - codecov --disable=gcov
  - docker build -t driver-license-verification .
