name: HealthCheck

on:
  push:
    branches:
      - main

jobs:
  test-e2e:
    name: Test e2e

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install packages
        run: yarn
      - name: Run e2e tests
        run: yarn test:e2e
